#!/usr/bin/env bash
set -e

URL="cdn.modrinth.com/data/b4aMFpUj/versions/wTw0dtYW/stdrive-1.0.1-1.20.1-1.0.1.jar"
DEST="libs/stdrive-1.0.1-1.20.1-1.0.1.jar"

mkdir -p libs
curl -L -o "${DEST}" "${URL}"
